mysqldb: 
    datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc\:mysql\://183.224.79.167\:3806/cloud_test?useUnicode\=true&characterEncoding\=utf-8
        username: root
        password: 123456
        
